# coding: utf-8

"""
    Order Details

    Retrieve information about current and past orders.  # noqa: E501

    OpenAPI spec version: v3
    Contact: api.contact@digikey.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import digikey.v3.ordersupport
from digikey.v3.ordersupport.models.api_error_response import ApiErrorResponse  # noqa: E501
from digikey.v3.ordersupport.rest import ApiException


class TestApiErrorResponse(unittest.TestCase):
    """ApiErrorResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testApiErrorResponse(self):
        """Test ApiErrorResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = digikey.v3.ordersupport.models.api_error_response.ApiErrorResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
