# coding: utf-8

"""
    Batch Product Details Api

    Retrieve list of product details from list of part numbers  # noqa: E501

    OpenAPI spec version: v3
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class PidVid(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'parameter_id': 'int',
        'value_id': 'str',
        'parameter': 'str',
        'value': 'str'
    }

    attribute_map = {
        'parameter_id': 'ParameterId',
        'value_id': 'ValueId',
        'parameter': 'Parameter',
        'value': 'Value'
    }

    def __init__(self, parameter_id=None, value_id=None, parameter=None, value=None):  # noqa: E501
        """PidVid - a model defined in Swagger"""  # noqa: E501

        self._parameter_id = None
        self._value_id = None
        self._parameter = None
        self._value = None
        self.discriminator = None

        if parameter_id is not None:
            self.parameter_id = parameter_id
        if value_id is not None:
            self.value_id = value_id
        if parameter is not None:
            self.parameter = parameter
        if value is not None:
            self.value = value

    @property
    def parameter_id(self):
        """Gets the parameter_id of this PidVid.  # noqa: E501

        The Id of the parameter.  # noqa: E501

        :return: The parameter_id of this PidVid.  # noqa: E501
        :rtype: int
        """
        return self._parameter_id

    @parameter_id.setter
    def parameter_id(self, parameter_id):
        """Sets the parameter_id of this PidVid.

        The Id of the parameter.  # noqa: E501

        :param parameter_id: The parameter_id of this PidVid.  # noqa: E501
        :type: int
        """

        self._parameter_id = parameter_id

    @property
    def value_id(self):
        """Gets the value_id of this PidVid.  # noqa: E501

        The Id of the value.  # noqa: E501

        :return: The value_id of this PidVid.  # noqa: E501
        :rtype: str
        """
        return self._value_id

    @value_id.setter
    def value_id(self, value_id):
        """Sets the value_id of this PidVid.

        The Id of the value.  # noqa: E501

        :param value_id: The value_id of this PidVid.  # noqa: E501
        :type: str
        """

        self._value_id = value_id

    @property
    def parameter(self):
        """Gets the parameter of this PidVid.  # noqa: E501

        The name of the parameter.  # noqa: E501

        :return: The parameter of this PidVid.  # noqa: E501
        :rtype: str
        """
        return self._parameter

    @parameter.setter
    def parameter(self, parameter):
        """Sets the parameter of this PidVid.

        The name of the parameter.  # noqa: E501

        :param parameter: The parameter of this PidVid.  # noqa: E501
        :type: str
        """

        self._parameter = parameter

    @property
    def value(self):
        """Gets the value of this PidVid.  # noqa: E501

        The name of the value.  # noqa: E501

        :return: The value of this PidVid.  # noqa: E501
        :rtype: str
        """
        return self._value

    @value.setter
    def value(self, value):
        """Sets the value of this PidVid.

        The name of the value.  # noqa: E501

        :param value: The value of this PidVid.  # noqa: E501
        :type: str
        """

        self._value = value

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(PidVid, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, PidVid):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
