# coding: utf-8

"""
    PartSearch Api

    Search for products and retrieve details and pricing.  # noqa: E501

    OpenAPI spec version: Ps2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class ProductWithSuggestions(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'product': 'ProductDetails',
        'suggested_products': 'list[Product]'
    }

    attribute_map = {
        'product': 'Product',
        'suggested_products': 'SuggestedProducts'
    }

    def __init__(self, product=None, suggested_products=None):  # noqa: E501
        """ProductWithSuggestions - a model defined in Swagger"""  # noqa: E501

        self._product = None
        self._suggested_products = None
        self.discriminator = None

        if product is not None:
            self.product = product
        if suggested_products is not None:
            self.suggested_products = suggested_products

    @property
    def product(self):
        """Gets the product of this ProductWithSuggestions.  # noqa: E501


        :return: The product of this ProductWithSuggestions.  # noqa: E501
        :rtype: ProductDetails
        """
        return self._product

    @product.setter
    def product(self, product):
        """Sets the product of this ProductWithSuggestions.


        :param product: The product of this ProductWithSuggestions.  # noqa: E501
        :type: ProductDetails
        """

        self._product = product

    @property
    def suggested_products(self):
        """Gets the suggested_products of this ProductWithSuggestions.  # noqa: E501


        :return: The suggested_products of this ProductWithSuggestions.  # noqa: E501
        :rtype: list[Product]
        """
        return self._suggested_products

    @suggested_products.setter
    def suggested_products(self, suggested_products):
        """Sets the suggested_products of this ProductWithSuggestions.


        :param suggested_products: The suggested_products of this ProductWithSuggestions.  # noqa: E501
        :type: list[Product]
        """

        self._suggested_products = suggested_products

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ProductWithSuggestions, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ProductWithSuggestions):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
