# coding: utf-8

"""
    Orders

    API operations for managing orders as well as refunds and incidents as they relate to the order  # noqa: E501

    OpenAPI spec version: suppliers-v1
    Contact: MarketplaceAPISupport@digikey.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class GetOrdersPage(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'orders': 'list[OrderExpanded]',
        'total_count': 'int',
        'total_sales': 'float'
    }

    attribute_map = {
        'orders': 'orders',
        'total_count': 'totalCount',
        'total_sales': 'totalSales'
    }

    def __init__(self, orders=None, total_count=None, total_sales=None):  # noqa: E501
        """GetOrdersPage - a model defined in Swagger"""  # noqa: E501

        self._orders = None
        self._total_count = None
        self._total_sales = None
        self.discriminator = None

        if orders is not None:
            self.orders = orders
        if total_count is not None:
            self.total_count = total_count
        if total_sales is not None:
            self.total_sales = total_sales

    @property
    def orders(self):
        """Gets the orders of this GetOrdersPage.  # noqa: E501


        :return: The orders of this GetOrdersPage.  # noqa: E501
        :rtype: list[OrderExpanded]
        """
        return self._orders

    @orders.setter
    def orders(self, orders):
        """Sets the orders of this GetOrdersPage.


        :param orders: The orders of this GetOrdersPage.  # noqa: E501
        :type: list[OrderExpanded]
        """

        self._orders = orders

    @property
    def total_count(self):
        """Gets the total_count of this GetOrdersPage.  # noqa: E501


        :return: The total_count of this GetOrdersPage.  # noqa: E501
        :rtype: int
        """
        return self._total_count

    @total_count.setter
    def total_count(self, total_count):
        """Sets the total_count of this GetOrdersPage.


        :param total_count: The total_count of this GetOrdersPage.  # noqa: E501
        :type: int
        """

        self._total_count = total_count

    @property
    def total_sales(self):
        """Gets the total_sales of this GetOrdersPage.  # noqa: E501


        :return: The total_sales of this GetOrdersPage.  # noqa: E501
        :rtype: float
        """
        return self._total_sales

    @total_sales.setter
    def total_sales(self, total_sales):
        """Sets the total_sales of this GetOrdersPage.


        :param total_sales: The total_sales of this GetOrdersPage.  # noqa: E501
        :type: float
        """

        self._total_sales = total_sales

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(GetOrdersPage, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, GetOrdersPage):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
