# coding: utf-8

"""
    ProductSearch Api

    ProductSearch Api  # noqa: E501

    OpenAPI spec version: v4
    Contact: dl_Agile_Team_B2B_API@digikey.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class TopCategory(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'root_category': 'TopCategoryNode',
        'category': 'TopCategoryNode',
        'score': 'float',
        'image_url': 'str'
    }

    attribute_map = {
        'root_category': 'RootCategory',
        'category': 'Category',
        'score': 'Score',
        'image_url': 'ImageUrl'
    }

    def __init__(self, root_category=None, category=None, score=None, image_url=None):  # noqa: E501
        """TopCategory - a model defined in Swagger"""  # noqa: E501
        self._root_category = None
        self._category = None
        self._score = None
        self._image_url = None
        self.discriminator = None
        if root_category is not None:
            self.root_category = root_category
        if category is not None:
            self.category = category
        if score is not None:
            self.score = score
        if image_url is not None:
            self.image_url = image_url

    @property
    def root_category(self):
        """Gets the root_category of this TopCategory.  # noqa: E501


        :return: The root_category of this TopCategory.  # noqa: E501
        :rtype: TopCategoryNode
        """
        return self._root_category

    @root_category.setter
    def root_category(self, root_category):
        """Sets the root_category of this TopCategory.


        :param root_category: The root_category of this TopCategory.  # noqa: E501
        :type: TopCategoryNode
        """

        self._root_category = root_category

    @property
    def category(self):
        """Gets the category of this TopCategory.  # noqa: E501


        :return: The category of this TopCategory.  # noqa: E501
        :rtype: TopCategoryNode
        """
        return self._category

    @category.setter
    def category(self, category):
        """Sets the category of this TopCategory.


        :param category: The category of this TopCategory.  # noqa: E501
        :type: TopCategoryNode
        """

        self._category = category

    @property
    def score(self):
        """Gets the score of this TopCategory.  # noqa: E501

        Category Score  # noqa: E501

        :return: The score of this TopCategory.  # noqa: E501
        :rtype: float
        """
        return self._score

    @score.setter
    def score(self, score):
        """Sets the score of this TopCategory.

        Category Score  # noqa: E501

        :param score: The score of this TopCategory.  # noqa: E501
        :type: float
        """

        self._score = score

    @property
    def image_url(self):
        """Gets the image_url of this TopCategory.  # noqa: E501

        URL for the Category image  # noqa: E501

        :return: The image_url of this TopCategory.  # noqa: E501
        :rtype: str
        """
        return self._image_url

    @image_url.setter
    def image_url(self, image_url):
        """Sets the image_url of this TopCategory.

        URL for the Category image  # noqa: E501

        :param image_url: The image_url of this TopCategory.  # noqa: E501
        :type: str
        """

        self._image_url = image_url

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(TopCategory, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, TopCategory):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
