# coding: utf-8

"""
    ProductSearch Api

    ProductSearch Api  # noqa: E501

    OpenAPI spec version: v4
    Contact: dl_Agile_Team_B2B_API@digikey.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class TopCategoryNode(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'int',
        'name': 'str',
        'product_count': 'int'
    }

    attribute_map = {
        'id': 'Id',
        'name': 'Name',
        'product_count': 'ProductCount'
    }

    def __init__(self, id=None, name=None, product_count=None):  # noqa: E501
        """TopCategoryNode - a model defined in Swagger"""  # noqa: E501
        self._id = None
        self._name = None
        self._product_count = None
        self.discriminator = None
        if id is not None:
            self.id = id
        if name is not None:
            self.name = name
        if product_count is not None:
            self.product_count = product_count

    @property
    def id(self):
        """Gets the id of this TopCategoryNode.  # noqa: E501

        Category Id  # noqa: E501

        :return: The id of this TopCategoryNode.  # noqa: E501
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this TopCategoryNode.

        Category Id  # noqa: E501

        :param id: The id of this TopCategoryNode.  # noqa: E501
        :type: int
        """

        self._id = id

    @property
    def name(self):
        """Gets the name of this TopCategoryNode.  # noqa: E501

        Category Name  # noqa: E501

        :return: The name of this TopCategoryNode.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this TopCategoryNode.

        Category Name  # noqa: E501

        :param name: The name of this TopCategoryNode.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def product_count(self):
        """Gets the product_count of this TopCategoryNode.  # noqa: E501

        Product count for the Category  # noqa: E501

        :return: The product_count of this TopCategoryNode.  # noqa: E501
        :rtype: int
        """
        return self._product_count

    @product_count.setter
    def product_count(self, product_count):
        """Sets the product_count of this TopCategoryNode.

        Product count for the Category  # noqa: E501

        :param product_count: The product_count of this TopCategoryNode.  # noqa: E501
        :type: int
        """

        self._product_count = product_count

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(TopCategoryNode, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, TopCategoryNode):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
