# coding: utf-8

"""
    PartSearch Api

    Search for products and retrieve details and pricing.  # noqa: E501

    OpenAPI spec version: v3
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class LimitedParameter(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'values': 'list[ValuePair]',
        'parameter_id': 'int',
        'parameter': 'str'
    }

    attribute_map = {
        'values': 'Values',
        'parameter_id': 'ParameterId',
        'parameter': 'Parameter'
    }

    def __init__(self, values=None, parameter_id=None, parameter=None):  # noqa: E501
        """LimitedParameter - a model defined in Swagger"""  # noqa: E501

        self._values = None
        self._parameter_id = None
        self._parameter = None
        self.discriminator = None

        if values is not None:
            self.values = values
        if parameter_id is not None:
            self.parameter_id = parameter_id
        if parameter is not None:
            self.parameter = parameter

    @property
    def values(self):
        """Gets the values of this LimitedParameter.  # noqa: E501

        List of values for the parameter that are contained in the products.  # noqa: E501

        :return: The values of this LimitedParameter.  # noqa: E501
        :rtype: list[ValuePair]
        """
        return self._values

    @values.setter
    def values(self, values):
        """Sets the values of this LimitedParameter.

        List of values for the parameter that are contained in the products.  # noqa: E501

        :param values: The values of this LimitedParameter.  # noqa: E501
        :type: list[ValuePair]
        """

        self._values = values

    @property
    def parameter_id(self):
        """Gets the parameter_id of this LimitedParameter.  # noqa: E501

        The Id of the parameter.  # noqa: E501

        :return: The parameter_id of this LimitedParameter.  # noqa: E501
        :rtype: int
        """
        return self._parameter_id

    @parameter_id.setter
    def parameter_id(self, parameter_id):
        """Sets the parameter_id of this LimitedParameter.

        The Id of the parameter.  # noqa: E501

        :param parameter_id: The parameter_id of this LimitedParameter.  # noqa: E501
        :type: int
        """

        self._parameter_id = parameter_id

    @property
    def parameter(self):
        """Gets the parameter of this LimitedParameter.  # noqa: E501

        The name of the parameter.  # noqa: E501

        :return: The parameter of this LimitedParameter.  # noqa: E501
        :rtype: str
        """
        return self._parameter

    @parameter.setter
    def parameter(self, parameter):
        """Sets the parameter of this LimitedParameter.

        The name of the parameter.  # noqa: E501

        :param parameter: The parameter of this LimitedParameter.  # noqa: E501
        :type: str
        """

        self._parameter = parameter

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(LimitedParameter, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, LimitedParameter):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
