# coding: utf-8

"""
    PartSearch Api

    Search for products and retrieve details and pricing.  # noqa: E501

    OpenAPI spec version: v3
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class ValuePair(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'value_id': 'str',
        'value': 'str'
    }

    attribute_map = {
        'value_id': 'ValueId',
        'value': 'Value'
    }

    def __init__(self, value_id=None, value=None):  # noqa: E501
        """ValuePair - a model defined in Swagger"""  # noqa: E501

        self._value_id = None
        self._value = None
        self.discriminator = None

        if value_id is not None:
            self.value_id = value_id
        if value is not None:
            self.value = value

    @property
    def value_id(self):
        """Gets the value_id of this ValuePair.  # noqa: E501

        The Id of the value.  # noqa: E501

        :return: The value_id of this ValuePair.  # noqa: E501
        :rtype: str
        """
        return self._value_id

    @value_id.setter
    def value_id(self, value_id):
        """Sets the value_id of this ValuePair.

        The Id of the value.  # noqa: E501

        :param value_id: The value_id of this ValuePair.  # noqa: E501
        :type: str
        """

        self._value_id = value_id

    @property
    def value(self):
        """Gets the value of this ValuePair.  # noqa: E501

        The name of the value.  # noqa: E501

        :return: The value of this ValuePair.  # noqa: E501
        :rtype: str
        """
        return self._value

    @value.setter
    def value(self, value):
        """Sets the value of this ValuePair.

        The name of the value.  # noqa: E501

        :param value: The value of this ValuePair.  # noqa: E501
        :type: str
        """

        self._value = value

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ValuePair, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ValuePair):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
