# coding: utf-8

"""
    PartSearch Api

    Search for products and retrieve details and pricing.  # noqa: E501

    OpenAPI spec version: v3
    Contact: api.support@digikey.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import digikey.v3.productinformation
from digikey.v3.productinformation.models.digi_reel_pricing import DigiReelPricing  # noqa: E501
from digikey.v3.productinformation.rest import ApiException


class TestDigiReelPricing(unittest.TestCase):
    """DigiReelPricing unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDigiReelPricing(self):
        """Test DigiReelPricing"""
        # FIXME: construct object with mandatory attributes with example values
        # model = digikey.v3.productinformation.models.digi_reel_pricing.DigiReelPricing()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
