# coding: utf-8

"""
    PartSearch Api

    Search for products and retrieve details and pricing.  # noqa: E501

    OpenAPI spec version: v3
    Contact: api.support@digikey.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import digikey.v3.productinformation
from digikey.v3.productinformation.models.basic_product import BasicProduct  # noqa: E501
from digikey.v3.productinformation.rest import ApiException


class TestBasicProduct(unittest.TestCase):
    """BasicProduct unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testBasicProduct(self):
        """Test BasicProduct"""
        # FIXME: construct object with mandatory attributes with example values
        # model = digikey.v3.productinformation.models.basic_product.BasicProduct()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
